default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ny_capital_home_development

test:
  <<: *default
  database: ny_capital_home_test
